# Generated by Django 4.1.6 on 2023-03-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharing', '0002_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='user',
            new_name='user_id',
        ),
    ]
