# Generated by Django 4.1.6 on 2023-03-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharing', '0003_rename_user_otp_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='user_id',
            new_name='user',
        ),
    ]
