# Generated by Django 4.1.6 on 2023-03-05 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharing', '0004_rename_user_id_otp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RideSharing.userinfo'),
        ),
    ]
