# Generated by Django 4.1.6 on 2023-03-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharing', '0005_alter_otp_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
    ]
