# Generated by Django 4.1.6 on 2023-03-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharing', '0007_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='test1',
        ),
    ]
