export const ADD_PHONENUMBER = 'ADD_PHONENUMBER';
export const ADD_CODE = 'ADD_CODE';
export const ADD_CONFIRM = 'ADD_CONFIRM';
export const ADD_ORIGIN_LOCATION = 'ADD_ORIGIN_LOCATION';
export const ADD_ORIGIN_DESCRIPTION = 'ADD_ORIGIN_DESCRIPTION';
export const ADD_DESTINATION_LOCATION = 'ADD_DESTINATION_LOCATION';
export const ADD_DESTINATION_DESCRIPTION = 'ADD_DESTINATION_DESCRIPTION';
export const ADD_CURRENT_LOCATION = 'ADD_CURRENT_LOCATION';